/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines used BLE-services.
 */
export interface BLEServiceSchemaDefinition {
  /**
   * Defines the version of the ble-services.yml file.
   */
  "file-version": string;
  /**
   * The list of defined BLE-services.
   */
  "ble-services": {
    service: {
      /**
       * Name of the service
       */
      name: string;
      uuid: string;
      description: string;
      /**
       * Additional information how to use this service formatted in markdown.
       */
      "application-note"?: string;
      /**
       * Link to the document describing a service that is defined by the BLE SIG.
       */
      "ble-sig-reference"?: string;
      "supported-characteristics": {
        /**
         * Specification of a characteristic
         */
        characteristic: {
          /**
           * Name of the characteristic
           */
          name: string;
          /**
           * UUID of the characteristic
           */
          uuid: string;
          description: string;
          /**
           * Data type of the characteristic value
           */
          "data-type": string;
          /**
           * List of devices that implement this characteristic
           */
          "implemented-by"?: string[];
          /**
           * The properties of this BLE characteristic
           */
          "access-properties": ("read" | "write" | "notify" | "indicate")[];
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
